name: Floristics
main: land.jay.floristics.Floristics
version: 2.6
api-version: 1.18
softdepend: [Towny]
commands:
    floristics:
        aliases: flo
        description: enable or disable growth in Towny towns
        usage: /floristics ...
